server:
  port: 8099

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://47.115.60.46:3306/user_center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: Qq48038411..
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.60.46:8848
        #配置元数据
        metadata:
          hello: world
          version: 0.1
#        namespace: 5a7fca12-1710-4fe9-8ce9-68329156cfdd
  zipkin:
    base-url: http://localhost:9411/
#    不要被nacos发现
    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0
rocketmq:
  name-server: 47.115.60.46:9876
  producer:
    group: test-group
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
jwt:
  secret: aaaaaaaaaaaaabbbbbbbbbbbbbccccccccccccccccc
  expire-time-in-second: 1209600