server:
  port: 8082
spring:
  application:
    name: content-center
  datasource:
    url: jdbc:mysql://47.115.60.46:3306/content_center
    hikari:
      username: root
      password: Qq48038411..
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.60.46:8848
  #    sentinel:
  #      transport:
  #        dashboard: localhost:8080
  main:
    allow-bean-definition-overriding: true
#        namespace: 5a7fca12-1710-4fe9-8ce9-68329156cfdd

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    #    一定是debug才能打印
    com.soft1851.share.content.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.soft1851.share.content.feignclient.interceptor.TokenInterceptor
  httpclient:
#    让feign使用apache httpclient做请求，而不是默认的urlconnection
    enabled: true
#    feign的最大连接数
    max-connections: 200
#    feign单个路径的最大连接数
    max-connections-per-route: 50
rocketmq:
  name-server: 47.115.60.46:9876
  producer:
    group: test-group
#    生产者方必须指定group