server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.60.46:8848
    gateway:
      discovery:
        locator:
#          gatewayͨ也要去网关注册发现
          enabled: true
      routes:
       - id: path_route
         uri: lb://user-center
         predicates:
           - Path=/users/**
       - id: path_routew2
         uri: lb://content-center
         predicates:
           - Path=/shares/**
       - id: path_route3
         uri: lb://content-center
         predicates:
           - Path=/notice/**
       - id: path_route4
         uri: lb://content-center
         predicates:
           - Path=/admin/shares/**
#           - Cookie=username,guorc
#           - Method=GET
#           - Between=2020-10-09T11:32:12.975035+08:00[Asia/Shanghai],2021-06-07T16:32:12.975035+08:00[Asia/Shanghai]
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace
